### ISSUE TITLE
Is the password suppose to be on open display

### ISSUE THREAD

**Issue by andreGarvin** [ozzie1998/rocket#1]
https://github.com/ozzie1998/rocket/blob/7d320b063f0aa7f0592fae3e684849649d25b292/knexfile.js#L9

**Comment by andreGarvin** [comment]
I would suggest to you do something like, `process.env.db_key`

**Comment by ozzie1998** [comment]
Meant to change that to ChangeMe, change it accordingly.

**Comment by andreGarvin** [comment]
Also, I am a college student as well, freshmen. Not sure where that stands in the education spectrum in England and COmp Sci major as well.

**Comment by ozzie1998** [comment]
Ahh, very good. I am currently trying to get the file upload to work for ‘npm publish’

**Comment by ozzie1998** [comment]
We can probably just use a json file. We will be easier for deployment.

**Comment by andreGarvin** [comment]
Yea that is how npm does it, they use the packge.json file to pull other dependencies and modules

**Comment by andreGarvin** [comment]
Aso did you look at my PR's @ozzie1998

**Comment by ozzie1998** [comment]
Yes, I’m going to rework the db operations, to external promisified
functions anyway.

**Comment by andreGarvin** [comment]
ARe you looking at my PR's ? I trying to help you with the code and simplify the code and helping with the code @ozzie1998

**Comment by ozzie1998** [comment]
Also, that is the password to my local mamp, you change it accordingly. will use a config file for future.
