### ISSUE TITLE
Should all people contribute, or just white men?

### ISSUE THREAD

**Issue by EvanCarroll** [ozzie1998/rocket#5]
Since this is a fork by a racist bigot who has political problems with policies of inclusion and in alignment with actual Nazis like Ian Miles Cheong, I'm just wondering if contributions by minorities religious and otherwise should be actively and clearly discouraged?

What do you the Aryans think?

**Comment by ozzie1998** [comment]
this is not a fork, it's all my own code. Any one can contribute, from whites to multicolored.

**Comment by EvanCarroll** [comment]
What about Muslims?

https://imgur.com/gallery/XLArm

**Comment by EvanCarroll** [comment]
I mean, NPM needs to be replaced because Isaac is nuts and thinks killing Nazis is permissible because if they get power, they kill millions and genocide is part of their platform. But, killing people who peacefully worship a different sky-god, that's fine. amirite?

I mean you don't care if you're a racist.

**Comment by ozzie1998** [comment]
I’m not a racist. I’m not sure what you’re trying to achieve here? Any ways, you aren’t stopping me from finishing Rocket. Regardless.

**Comment by ozzie1998** [comment]
On a side note, they are horrible to their women. Also, they are killing many many people who refuse to switch to Muslim. Please to away, if you’ve got nothing constructive to say.

**Comment by EvanCarroll** [comment]
Alt-right snowflakes from /r/The_Donald learned how to use github. It's a sad day.

**Comment by ozzie1998** [comment]
Relating to the comments of my alt account, I was going through a mental issues phase.

**Comment by ozzie1998** [comment]
Locking this.

**Comment by ozzie1998** [comment]
Uhh?
