### ISSUE TITLE
Why are we keeping track of dependincies in the database?

### ISSUE THREAD

**Issue by ozzie1998** [ozzie1998/rocket#6]
This info is stored in the package.json, we will be unpacking the project any way. So can read in the package.json before we pack and serve the download

**Comment by EvanCarroll** [comment]
[Package.json is an NPM thing](https://docs.npmjs.com/files/package.json). If you're going to write an alternative to NPM, you should

1. Delete it entirely.
2. Add the `node_modules/` into the repository.

If you're going to keep it I suggest naming it to `ozziePeck.json` so people know you don't like npm.

**Comment by ozzie1998** [comment]
Please leave. Thanks.

**Comment by ozzie1998** [comment]
What’s your problem? Don’t like Rocket, then there’s a simple solution to it. Leave. Go back to  pathetic NPM. And bathe in your CEOs mental illness.

**Comment by ozzie1998** [comment]
Okay, I've decided this would allow quicker serving of packages. Going to store the first level of dependencies.
